import{S as $,i as f,a as b}from"./assets/vendor-5401a4b0.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const q=document.querySelector(".form"),n=document.querySelector(".gallery"),L=document.querySelector("input");document.querySelector(".container");const m=document.querySelector(".btn-load"),x=document.querySelector(".loading-text");let d=1,p=15,h=0;const u=()=>{x.style.display="block"},g=()=>{x.style.display="none"},T=()=>{m.style.display="block"},i=()=>{m.style.display="none"},S={captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",animation:250},w=new $(".gallery a",S);let c;function v(o){return`
        <li class="gallery-item">
            <a href="${o.webformatURL}">
                <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}">
            </a>
            <div class="image-details">
                <div class="image-text">
                    <p><b class="image-text-width">Likes: </b>${o.likes}</p>
                    <p><b class="image-text-width">Views: </b>${o.views}</p>
                    <p><b class="image-text-width">Comments: </b>${o.comments}</p>
                    <p><b class="image-text-width">Downloads: </b>${o.downloads}</p>
                </div>
            </div>
        </li>`}q.addEventListener("submit",async o=>{d=1,p=15,o.preventDefault(),u(),i(),n.innerHTML="";const a="42400311-c577e995298d386a6e7116ddb";if(c=L.value.trim(),!c){f.error({backgroundColor:"#EF4040",message:"Please. enter a search query!",position:"topRight"}),g(),i();return}try{const r=(await b.get(`https://pixabay.com/api/?key=${a}&q=${encodeURIComponent(c)}&image_type=photo&orientation=horizontal&safesearch=true&page=1&per_page=${p}`)).data;if(!r.hits.length)f.error({title:"",backgroundColor:"#EF4040",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),i();else{u();const e=r.hits.map(v).join("");n.insertAdjacentHTML("afterbegin",e),w.refresh(),T()}}catch(s){console.log(s)}finally{g()}});m.addEventListener("click",async o=>{d++,n.innerHTML="",u(),i(),o.preventDefault();const a="42400311-c577e995298d386a6e7116ddb";c=L.value.trim();try{const r=(await b.get(`https://pixabay.com/api/?key=${a}&q=${encodeURIComponent(c)}&image_type=photo&orientation=horizontal&safesearch=true&page=${d}&per_page=${p}`)).data;if(r.hits.length){const e=r.hits.map(v).join("");n.insertAdjacentHTML("afterbegin",e),w.refresh();const t=document.querySelector(".gallery-image").getBoundingClientRect().height;if((()=>{window.scrollBy({top:2*t,behavior:"smooth"})})(),u(),h=r.totalHits,h<=p*d){const y=document.createElement("div");y.innerText="We're sorry, but you've reached the end of search results.",n.appendChild(y)}i()}}catch(s){console.log(s)}finally{g(),showLoadMoreButtonLoadingText()}});
//# sourceMappingURL=commonHelpers.js.map
