import{S as q,i as h,a as b}from"./assets/vendor-5401a4b0.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const S=document.querySelector(".form"),p=document.querySelector(".gallery"),x=document.querySelector("input");document.querySelector(".container");const g=document.querySelector(".btn-load"),L=document.querySelector(".loading-text");let d=1,n=15,f=0;const u=()=>{L.style.display="block"},m=()=>{L.style.display="none"},w=()=>{g.style.display="block"},a=()=>{g.style.display="none"},T={captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",animation:250},v=new q(".gallery a",T);let c;function $(o){return`
        <li class="gallery-item">
            <a href="${o.webformatURL}">
                <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}">
            </a>
            <div class="image-details">
                <div class="image-text">
                    <p><b class="image-text-width">Likes: </b>${o.likes}</p>
                    <p><b class="image-text-width">Views: </b>${o.views}</p>
                    <p><b class="image-text-width">Comments: </b>${o.comments}</p>
                    <p><b class="image-text-width">Downloads: </b>${o.downloads}</p>
                </div>
            </div>
        </li>`}S.addEventListener("submit",async o=>{d=1,n=15,o.preventDefault(),u(),a(),p.innerHTML="";const s="42400311-c577e995298d386a6e7116ddb";if(c=x.value.trim(),!c){h.error({backgroundColor:"#EF4040",message:"Please. enter a search query!",position:"topRight"}),m(),a();return}try{const r=(await b.get(`https://pixabay.com/api/?key=${s}&q=${encodeURIComponent(c)}&image_type=photo&orientation=horizontal&safesearch=true&page=1&per_page=${n}`)).data;if(!r.hits.length)h.error({title:"",backgroundColor:"#EF4040",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),a();else{const e=r.hits.map($).join("");p.insertAdjacentHTML("beforeend",e),v.refresh(),r.hits.length<n?a():w()}}catch{return"error"}finally{m()}});g.addEventListener("click",async o=>{d++,u(),a();const s="42400311-c577e995298d386a6e7116ddb";c=x.value.trim();try{const r=(await b.get(`https://pixabay.com/api/?key=${s}&q=${encodeURIComponent(c)}&image_type=photo&orientation=horizontal&safesearch=true&page=${d}&per_page=${n}`)).data;if(r.hits.length){const e=r.hits.map($).join("");p.insertAdjacentHTML("beforeend",e),v.refresh(),r.hits.length<n?a():w();const t=document.querySelector(".gallery-image").getBoundingClientRect().height;if((()=>{window.scrollBy({top:2*t,behavior:"smooth"})})(),u(),f=r.totalHits,f<=n*d){const y=document.createElement("div");y.innerText="We're sorry, but you've reached the end of search results.",p.appendChild(y),a()}}}catch{return"error"}finally{m()}});
//# sourceMappingURL=commonHelpers.js.map
